### ISSUE TITLE
Add a target project option

### ISSUE THREAD

**Issue by QbDesu** [kuiperzone/Publish-AppImage#2]
Some projects have multiple project file because they e.g. target multiple platforms which need different treatment. When there is multiple .csproj or whatever files in the directory the publish command requires adding the path to the target project as a parameter. Unfortunately I don't see a way to do this with this script so I modified the script to change the publish command.

I would create a PR myself but unfortunately I understand hardly anything about bash so I don't really know how I would go about it. For the specific project I worked on I just added the hardcoded project file at the end of the command in the appropriate file but I expect it would not be difficult to do it dynamically with a bit of understanding of shell scripting which I do not have.

Either way, thank you for this tool, it helped me a lot!

**Comment by kuiperzone** [comment]
Hi Qb,

If I understand you correctly, you can target the specific project with the following parameter:

`DOTNET_PROJECT_PATH`

Note that you can have multiple `conf` files targeting different projects and specify the file at the command line.

Thank you for the feedback. Glad it was useful.

**Comment by QbDesu** [comment]
Oh, I could have seen that if I had read the code a little further, and yes it's exactly what I meant. It's not documented in the readme but still I even looked at the code. Thank you very much. And as I said, yeah it was really helpful.
