### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/Publish-AppImage#4]
`./publish-appimage.conf -r win-x64 -k zip`

I think `.conf` shouldn't be here.

Then it results in this

`dotnet publish -r win-x64 -c Release -r linux-x64 --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -o "bin/AppImages/AppDir"`

I think that's wrong as it fails

`-r win-x64 -r linux-x64`

**Comment by kuiperzone** [comment]
You are right about the ".conf" in the given examples (which shouldn't be there). Will correct.

However, I'm not able to repeat:

    [kuiper@vendetta Publish-AppImage]$ ./publish-appimage -r win-x64 -k zip
    Publish-AppImage for .NET, 1.1.0
    Copyright 2021 Andy Thomas
    
    APP MAIN: HelloWorld
    APP ID: net.example.HelloWorld
    APP VERSION: 
    OUTPUT: AppImages/HelloWorld-win-x64.zip
    
    Build Commands:

    dotnet publish -r win-x64 -c Release --self-contained true -p:DebugType=None -p:DebugSymbols=false -o "AppImages/AppDir"
    
    (cd "AppImages/AppDir" && zip -r "/mnt/DEVEL-1TB/GITHUB/Publish-AppImage/AppImages/HelloWorld-win-x64.zip" ./)

Seems fine.

**Comment by mysteryx93** [comment]
Could the extra args be coming from elsewhere in the solution or project files?

btw I found out that the app doesn't quite work when compiled on Linux for Windows due to a bug... so the Windows build needs to be published from Windows anyway

**Comment by mysteryx93** [comment]
Found the problem to this one

`DOTNET_PUBLISH_ARGS="-c Release -r linux-x64 --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:PublishSingleFile=false -p:PublishTrimmed=true -p:TrimMode=link"`

I don't know why I've put `-r linux-x64` in here, but that's not in your conf file. The error was from my side. Closing this.
