### ISSUE TITLE
PKG_VERSION_FLAG not working

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/Publish-AppImage#5]
`PKG_VERSION_FLAG=true` doesn't work.

**Comment by kuiperzone** [comment]
This is working as intended, but unless you also specify a version at the command line, it will do nothing.

With PKG_VERSION_FLAG set to true, see, below:

    [kuiper@vendetta Publish-AppImage]$ ./publish-appimage -x 1.2.3
    Publish-AppImage for .NET, 1.1.0
    Copyright 2021 Andy Thomas

    APP MAIN: HelloWorld
    APP ID: net.example.HelloWorld
    APP VERSION: 1.2.3
    OUTPUT: AppImages/HelloWorld-1.2.3-x86_64.AppImage

See the OUTPUT filename now has the version?

**Comment by mysteryx93** [comment]
btw if an AppImage is installed on the system (with AppImageLauncher) and I run an updated AppImage, is it supposed to install a 2nd copy, or replace/update the existing one?

(and for it to behave nicely, supplying the version info is probably required?)

**Comment by kuiperzone** [comment]
I haven't tried AppImageLauncher, but would think also supplying the version is a good idea.

**Comment by mysteryx93** [comment]
I've been working on scripts to publish a series of apps for Windows, Linux, MacOS...

It's pretty easy to read AssemblyVersion directly from the csproj file. No more need to pass version as command-line argument.

Is it doing this to set on the AppImage?

**Comment by kuiperzone** [comment]
There is an APP_VERSION in the conf file. It does not read it from csproj. This is passed to dotnet publish as "p:Version" and is used to set the variable VERSION which is read by appimage tool.

**Comment by mysteryx93** [comment]
Thing is; I'd rather avoid having to update the conf file each time I want to deploy my app. This is prone to errors.

Particularly, I'm deploying 3 apps at the same time, for Windows, Linux, MacOS. AssemblyVersion in csproj is where I set the version... if I need to go around and do a bunch of manual edits before publish, I can easily forget something. I could automate the editing of the conf file, but that's not the ideal solution.

Edit: I see from your example above that I can provide the version from the command-line. That's what I should do.

Edit2: -x argument is not documented in your README.md. It's not recognized either as a valid argument. -v is something else.

Does the AppImage itself needs to store its version information?

**Comment by kuiperzone** [comment]
This was something I thought about and decided to allow optional specification of the version at the dotnet publish command.

Some of my projects have 20 or so projects. Which project should the bash script look in for the version number?

Also note, the "-x" argument was present but was removed and replaced with a field in the config in a previous release. Re-adding the ability to specify the version at the command line (as well as in the conf file) is something I would consider. But trying to reliably get a bash script to determine the app version from one or more dotnet project files is not the approach I would choose.
