### ISSUE TITLE
Set project path with command-line

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/Publish-AppImage#8]
I have a solution that contains various projects.

I'd like to be able to include the script once at the root level and call it to compile the various projects. Each project folder contains a .conf file. Is this currently possible?

    publish-appimage Player432hz
    publish-appimage Converter432hz

**Comment by kuiperzone** [comment]
Sure. You can one of two things (or both).

1. You can place the bash utility script somewhere else on your system and add it to your path. When you call it, it will look (by default) for the publish-appimage.conf file in the working directory (i.e. where your PWD at the terminal).

Or:

2. You can specify the conf file at the command line (which will override the default). I.e.

./publish-appimage -f other-file.conf

or let's say:

./publish-appimage -f subdir/other-file.conf


Hope this helps. :)
