### ISSUE TITLE
DOTNET_PROJECT_PATH="../" compiles bin in .conf directory

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/Publish-AppImage#9]
I tried adding 

     DOTNET_PROJECT_PATH="../"

It causes the bin to be compiled within the .conf directory instead of in the project directory.

**Comment by kuiperzone** [comment]
Can't look at this in detail now.

But I'm wondering whether supplying "dotnet publish" with a directory causes it to change its working directory. If so, you may be able to solve this by passing the path to the solution or project file, rather than a directory.

Will take a look next week.

**Comment by mysteryx93** [comment]
I've done this and it works

    dotnet publish ./MyAppFolder [other args]

**Comment by mysteryx93** [comment]
As I'm working on my publish scripts, I would find it useful to be able to specify the output AppImage path from the command-line. Otherwise I need to "guess" the suffix you append for each runtime.

**Comment by kuiperzone** [comment]
>Otherwise I need to "guess" the suffix you append for each runtime.

Can you explain?

**Comment by mysteryx93** [comment]
linux-x64 results in `x86_64` suffix, linus-arm64 results in `aarch64` suffix. I need to "know" that (and assume it will never change) so that I know where to pick up the output file.

**Comment by kuiperzone** [comment]
> linux-x64 results in `x86_64` suffix, linus-arm64 results in `aarch64` suffix. I need to "know" that (and assume it will never change) so that I know where to pick up the output file.

I've added an "--output" command argument to allow specification of the output filename.
